version: '3'

services:
  web:
    build: .
    container_name: web_service
    ports:
      - "8000:80"
    volumes:
      - "./www:/var/www/html"
    depends_on:
      - mysql
  mysql :
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test